spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/mobilelele?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 5MB
    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
  sql:
    init:
      mode: never
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  #Cloudinary Properties
  #cloudinary:
  #api-key:
  #api-secret:
  #cloud-name:

  mail:
    mobilele: "mobilele@test.com"
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: ${mailUsername}
    password: ${mailPassword}

mobilele:
  default.admin.pass: ${DEFAULT_ADMIN_PASS:root}
  remember.me.key: ${REMEBER_ME_KEY:topsecret}

logging:
  level:
    #    org.springframework: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.org.jdbc.bind: TRACE

open.exchange.rates:
  schema: https
  host: openexchangerates.org
  path: /api/latest.json
  app_id: ${OPEN_EXCHANGE_APP_ID:test}
  symbols: EUR,BGN
  enabled: false

management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"


google.recaptcha:
    siteKey: ${GOOGLE_RECAPTCHA_SITE_KEY}
    secretKey: ${GOOGLE_RECAPTCHA_SECRET_KEY}

